export const tracksList = [
    {
      id: 0,
      nameOfTheSong: "Guilt",
      additionToTheSong: "",
      singer: "Nero",
      musicAlbum: "Welcome Reality",
      trackDuration: "4:44",
    },
    {
      id: 1,
      nameOfTheSong: "Elektro",
      additionToTheSong: "",
      singer: "Dynoro, Outwork, Mr. Gee",
      musicAlbum: "Elektro",
      trackDuration: "2:22",
    },
    {
      id: 2,
      nameOfTheSong: "I’m Fire",
      additionToTheSong: "",
      singer: "Ali Bakgor",
      musicAlbum: "I’m Fire",
      trackDuration: "2:22",
    },
    {
      id: 3,
      nameOfTheSong: "Non Stop",
      additionToTheSong: "(Remix)",
      singer: "Стоункат, Psychopath",
      musicAlbum: "Non Stop",
      trackDuration: "4:12",
    },
    {
      id: 4,
      nameOfTheSong: "Run Run",
      additionToTheSong: "(feat. AR/CO)",
      singer: "Jaded, Will Clarke, AR/CO",
      musicAlbum: "Run Run",
      trackDuration: "2:54",
    },
    {
      id: 5,
      nameOfTheSong: "Eyes on Fire",
      additionToTheSong: "(Zeds Dead Remix)",
      singer: "Blue Foundation, Zeds Dead",
      musicAlbum: "Eyes on Fire",
      trackDuration: "5:20",
    },
    {
      id: 6,
      nameOfTheSong: "Mucho Bien",
      additionToTheSong: "(Hi Profile Remix)",
      singer: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
      musicAlbum: "Mucho Bien",
      trackDuration: "3:41",
    },
    {
      id: 7,
      nameOfTheSong: "Knives n Cherries",
      additionToTheSong: "",
      singer: "minthaze",
      musicAlbum: "Captivating",
      trackDuration: "1:48",
    },
    {
      id: 8,
      nameOfTheSong: "Knives n Cherries",
      additionToTheSong: "",
      singer: "minthaze",
      musicAlbum: "Captivating",
      trackDuration: "1:48",
    },
    {
      id: 9,
      nameOfTheSong: "Knives n Cherries",
      additionToTheSong: "",
      singer: "minthaze",
      musicAlbum: "Captivating",
      trackDuration: "1:48",
    },
    {
      id: 10,
      nameOfTheSong: "Knives n Cherries",
      additionToTheSong: "",
      singer: "minthaze",
      musicAlbum: "Captivating",
      trackDuration: "1:48",
    },
    {
      id: 11,
      nameOfTheSong: "Knives n Cherries",
      additionToTheSong: "",
      singer: "minthaze",
      musicAlbum: "Captivating",
      trackDuration: "1:48",
    },
    {
      id: 12,
      nameOfTheSong: "Knives n Cherries",
      additionToTheSong: "",
      singer: "minthaze",
      musicAlbum: "Captivating",
      trackDuration: "1:48",
    },
    {
      id: 13,
      nameOfTheSong: "Knives n Cherries",
      additionToTheSong: "",
      singer: "minthaze",
      musicAlbum: "Captivating",
      trackDuration: "1:48",
    },
    {
      id: 14,
      nameOfTheSong: "How Deep Is Your Love",
      additionToTheSong: "",
      singer: "Calvin Harris, Disciples",
      musicAlbum: "How Deep Is Your Love",
      trackDuration: "3:32",
    },
    {
      id: 15,
      nameOfTheSong: "Morena",
      additionToTheSong: "",
      singer: "Tom Boxer",
      musicAlbum: "Soundz Made in Romania",
      trackDuration: "3:36",
    },
    {
      id: 16,
      nameOfTheSong: "",
      additionToTheSong: "",
      singer: "",
      musicAlbum: "",
      trackDuration: "",
    },
  ];
  